export const SUCCESS_SUMMARY = "";
export const FAIL_SUMMARY = "";
export const USER_CREATE_SUCCESS = "";
export const USER_CREATE_FAILED = "";
export const USER_EDIT_SUCCESS = "";
export const USER_EDIT_FAILED = "";
export const USER_RESETPASSWORK_SUCCESS = "";
export const USER_RESETPASSWORK_FAILED = "";
export const USER_DISABLE_SUCCESS = "";
export const USER_DISABLE_FAILED = "";
export const USER_FORGOTPASS_SUCCESS = "";
export const USER_FORGOTPASS_FAILED = "";
export const LOCATION_CREATE_SUCCESS = "";
export const LOCATION_CREATE_FAILED = "";
export const LOCATION_EDIT_SUCCESS = "";
export const LOCATION_EDIT_FAILED = "";
export const LOCATION_DISABLE_SUCCESS = "";
export const LOCATION_DISABLE_FAILED = "";
export const MAINTENANCEWORKER_CREATE_SUCCESS = "";
export const MAINTENANCEWORKER_CREATE_FAILED = "";
export const MAINTENANCEWORKER_EDIT_SUCCESS = "";
export const MAINTENANCEWORKER_EDIT_FAILED = "";
export const MAINTENANCEWORKER_DISABLE_SUCCESS = "";
export const MAINTENANCEWORKER_DISABLE_FAILED = "";


export default {
    SUCCESS_SUMMARY,
    FAIL_SUMMARY,
    USER_CREATE_SUCCESS,
    USER_CREATE_FAILED,
    USER_EDIT_SUCCESS,
    USER_EDIT_FAILED,
    USER_RESETPASSWORK_SUCCESS,
    USER_RESETPASSWORK_FAILED,
    USER_DISABLE_SUCCESS,
    USER_DISABLE_FAILED,
    LOCATION_CREATE_SUCCESS,
    LOCATION_CREATE_FAILED,
    LOCATION_EDIT_SUCCESS,
    LOCATION_EDIT_FAILED,
    LOCATION_DISABLE_SUCCESS,
    LOCATION_DISABLE_FAILED,
    MAINTENANCEWORKER_CREATE_SUCCESS,
    MAINTENANCEWORKER_CREATE_FAILED,
    MAINTENANCEWORKER_EDIT_SUCCESS,
    MAINTENANCEWORKER_EDIT_FAILED,
    MAINTENANCEWORKER_DISABLE_SUCCESS,
    MAINTENANCEWORKER_DISABLE_FAILED,
    USER_FORGOTPASS_SUCCESS,
    USER_FORGOTPASS_FAILED
};