export const SUCCESS_SUMMARY = "";
export const FAIL_SUMMARY = "";
export const USER_CREATE_SUCCESS = "Create Account Success";
export const USER_CREATE_FAILED = "Create Account Failed";
export const USER_EDIT_SUCCESS = "Edit Account Success";
export const USER_EDIT_FAILED = "Edit Account Failed";
export const USER_RESETPASSWORK_SUCCESS = "Reset Password Success";
export const USER_RESETPASSWORK_FAILED = "Reset Password Failed";
export const USER_DISABLE_SUCCESS = "Disable Account Success";
export const USER_DISABLE_FAILED = "Disable Account Failed";
export const USER_FORGOTPASS_SUCCESS = "";
export const USER_FORGOTPASS_FAILED = "";
export const LOCATION_CREATE_SUCCESS = "Create Area Success";
export const LOCATION_CREATE_FAILED = "Create Area Failed";
export const LOCATION_EDIT_SUCCESS = "Edit Area Success";
export const LOCATION_EDIT_FAILED = "Edit Area Failed";
export const LOCATION_DISABLE_SUCCESS = "Disable Area Success";
export const LOCATION_DISABLE_FAILED = "Disable Area Failed";
export const MAINTENANCEWORKER_CREATE_SUCCESS = "Create Repairer Success";
export const MAINTENANCEWORKER_CREATE_FAILED = "Create Repairer Failed";
export const MAINTENANCEWORKER_EDIT_SUCCESS = "Edit Repairer Success";
export const MAINTENANCEWORKER_EDIT_FAILED = "Edit Repairer Failed";
export const MAINTENANCEWORKER_DISABLE_SUCCESS = "Disable Repairer Success";
export const MAINTENANCEWORKER_DISABLE_FAILED = "Disable Repairer Failed";

export const NOTIFICATION_CLEAR_SUCCESS = "";
export const NOTIFICATION_CLEAR_FAILED = "";
export const CRACK_UPDATE_SUCCESS = "";
export const CRACK_UPDATE_FAILED = "";

export const VIDEO_DELETE_SUCCESS = "";
export const VIDEO_DELETE_FAILED = "";

export const USER_LOGIN_FAILED = "";

export const USER_CHANGE_PASSWORD_SUCCESS = "";
export const USER_CHANGE_PASSWORD_FAILED = "";

export const USER_CHANGE_CONFIRM_FORGOTPASSWORD_SUCCESS = "";
export const USER_CHANGE_CONFIRM_FORGOTPASSWORD_FAILED = "";

export const USER_UPDATE_AREA_SUCCESS = "";
export const USER_UPDATE_AREA_FAILED = "";

export const CRACK_REJECT_SUCCESS = "";
export const CRACK_CONFIRM_SUCCESS = "";
export const CRACK_CONFIRM_FAILED = "";

export default {
    SUCCESS_SUMMARY,
    FAIL_SUMMARY,
    USER_CREATE_SUCCESS,
    USER_CREATE_FAILED,
    USER_EDIT_SUCCESS,
    USER_EDIT_FAILED,
    USER_RESETPASSWORK_SUCCESS,
    USER_RESETPASSWORK_FAILED,
    USER_DISABLE_SUCCESS,
    USER_DISABLE_FAILED,
    LOCATION_CREATE_SUCCESS,
    LOCATION_CREATE_FAILED,
    LOCATION_EDIT_SUCCESS,
    LOCATION_EDIT_FAILED,
    LOCATION_DISABLE_SUCCESS,
    LOCATION_DISABLE_FAILED,
    MAINTENANCEWORKER_CREATE_SUCCESS,
    MAINTENANCEWORKER_CREATE_FAILED,
    MAINTENANCEWORKER_EDIT_SUCCESS,
    MAINTENANCEWORKER_EDIT_FAILED,
    MAINTENANCEWORKER_DISABLE_SUCCESS,
    MAINTENANCEWORKER_DISABLE_FAILED,
    USER_FORGOTPASS_SUCCESS,
    USER_FORGOTPASS_FAILED,
    NOTIFICATION_CLEAR_SUCCESS,
    NOTIFICATION_CLEAR_FAILED,
    CRACK_UPDATE_SUCCESS,
    CRACK_UPDATE_FAILED,
    VIDEO_DELETE_SUCCESS,
    VIDEO_DELETE_FAILED,
    USER_LOGIN_FAILED,
    USER_CHANGE_PASSWORD_SUCCESS,
    USER_CHANGE_PASSWORD_FAILED,
    USER_CHANGE_CONFIRM_FORGOTPASSWORD_SUCCESS,
    USER_CHANGE_CONFIRM_FORGOTPASSWORD_FAILED,
    USER_UPDATE_AREA_SUCCESS,
    USER_UPDATE_AREA_FAILED,
    CRACK_REJECT_SUCCESS,
    CRACK_CONFIRM_FAILED
};